server:
  base_url: "https://abcdef123.eu.ngrok.io"
  path_prefix: "/vlxrobot"
  websocket_path: "/ws"
  port: "8000"
  test_port: "8001"

database:
  host: "localhost"
  port: 5432
  user: "postgres_user"
  password: "LA_TUA_PASSWORD_SEGRETA_DB"
  dbname: "obs_overlay_db"
  # 'disable', 'require', 'verify-full'
  sslmode: "disable" 

# Recommended to use 2 different accounts, or at least 2 difrerent tokens
# You can create token with https://twitchtokengenerator.com/
twitch:
  client_id: "IL_TUO_CLIENT_ID_TWITCH"
  client_secret: "IL_TUO_CLIENT_SECRET_TWITCH"
  webhook_secret: "UNA_FRASE_SEGRETA_MOLTO_LUNGA_E_CASUALE_PER_I_WEBHOOK"
  user_access_token: "il_token_lungo_che_hai_appena_copiato"
  chat:
    bot_username: "bot_name"
    bot_token: "oauth:IL_TUO_TOKEN"
    channel_to_join: "channel_name"
    command_cooldown: 15  # General cooldown in seconds (default 15)

  # YouTube APIs
youtube:
  api_key: ""  # Leave empty to disable YouTube module
  channel_id: "UC..."
