server:
  base_url: "https://abcdef123.eu.ngrok.io"
  path_prefix: "/vlxrobot"
  websocket_path: "/ws"
  port: "8000"
  test_port: "8001"
  overlay_volume: 50 # Master volume for overlays (0-100%)

database:
  host: "localhost"
  port: 5432
  user: "postgres_user"
  password: "YOUR_DB_SECRET_PASSWORD"
  dbname: "obs_overlay_db"
  sslmode: "disable" # Options: 'disable', 'require', 'verify-full'

twitch:
  client_id: "YOUR_TWITCH_CLIENT_ID"
  client_secret: "YOUR_TWITCH_CLIENT_SECRET"
  webhook_secret: "YOUR_RANDOM_LONG_SECRET_STRING"
  user_access_token: "your_generated_user_token"
  chat:
    bot_username: "BotAccountName"
    bot_token: "oauth:YOUR_BOT_TOKEN"
    channel_to_join: "TargetChannel"
    command_cooldown: 15

youtube:
  api_key: "" # Leave empty to disable YouTube module
  channel_id: "UC..."
  polling_interval: 5
  monitor:
    channel_ids: []
